version: '3.8'
services:
  llm-enrichment-api:
    build: .
    container_name: llm_enrichment_api
    env_file:
      - .env
    ports:
      - "8000:8000"
    restart: unless-stopped
    environment:
      - LLM_PROVIDER=gemini
      - LLM_MODEL=gemini-2.0-flash
    volumes:
      - /var/ossec/logs/alerts:/var/ossec/logs/alerts:ro
      - ./logs:/app/logs
